app: fullstack
component: website@1.0.0
name: fullstack-site

inputs:
  src:
    src: ./
    hook: npm run build
    dist: build
  # domain: ${env:domain} Uncomment this when you want to use a custom domain