app: fullstack
component: express@dev
name: api

inputs:
  # Express application source code.
  src: ./
  # Permissions required for the AWS Lambda function to interact with other resources
  roleName: ${output:permissions.name}
  # Enable this when you want to set a custom domain.
  # domain: api.${env:domain}
  # Enabling this auto-generates an OpenAPI spec each time this is deployed.  Note: this feature is still experimental.
  openApi: true
  # Environment variables
  env:
    # AWS DynamoDB Table name. Needed for the code to access it.
    db: ${output:database.name}
    # AWS DynamoDB Table Index name. Needed for the code to access it.
    dbIndex1: ${output:database.indexes.gsi1.name}
    # A secret token to sign the JWT tokens with.
    tokenSecret: secret_1234 # Change to secret via environment variable: ${env:tokenSecret}